# Generated by Django 5.2.5 on 2025-08-19 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve_id", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                ("dependency_name", models.CharField(max_length=255)),
                (
                    "cvss_v3_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "cvss_v3_vector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cvss_v2_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "cvss_v2_vector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("published_date", models.DateField()),
                ("last_modified_date", models.DateField()),
                ("references", models.JSONField(default=list)),
                ("threat_feed", models.CharField(max_length=100)),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this CVE has been resolved by the user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cve_data",
                "indexes": [
                    models.Index(
                        fields=["user", "cve_id"], name="cve_data_user_id_225a81_idx"
                    ),
                    models.Index(
                        fields=["dependency_name"], name="cve_data_depende_a7e899_idx"
                    ),
                    models.Index(
                        fields=["cvss_v3_score"], name="cve_data_cvss_v3_56088b_idx"
                    ),
                    models.Index(
                        fields=["published_date"], name="cve_data_publish_ae483a_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="cve_data_resolve_b44d57_idx"
                    ),
                ],
                "unique_together": {("user", "cve_id")},
            },
        ),
    ]
