# Generated by Django 5.2.5 on 2025-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cve",
            name="cve_id",
            field=models.CharField(max_length=20),
        ),
    ]
