# Generated by Django 5.2.5 on 2025-08-25 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_cve_cve_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cve",
            name="cve_data_resolve_b44d57_idx",
        ),
        migrations.RemoveField(
            model_name="cve",
            name="resolved",
        ),
        migrations.AddField(
            model_name="cve",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("started", "Started"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="not_started",
                help_text="Current status of this CVE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(fields=["status"], name="cve_data_status_a6bacf_idx"),
        ),
    ]
